---
# file: roles/vac/tasks/configure_iptables.yml

# configure iptables to allow input from virbr1
# will overwrite any existing iptables.
- name: ensure iptables is configured
  template: src=iptables/iptables.j2 dest=/etc/sysconfig/iptables
  notify: restart iptables
