---
# handlers file for vac

- name: restart libvirtd
  service: name=libvirtd state=restarted

- name: restart iptables
  service: name=iptables state=restarted

- name: restart networking
  service: name=network state=restarted
